### ISSUE TITLE
Base64 encode/decode functions are bugged

### ISSUE THREAD

**Issue by Jacob-Lockwood** [bsoelch/OneChar.js#2]
https://github.com/bsoelch/OneChar.js/blob/e625865f114e20bd38929d2394b0da3fbdfe7907/index.html#L48C1-L55

I'm pretty sure there's a bug in both of these functions: they call `string.replace` with a string as the first parameter rather than RegEx, meaning that *only the first occurrence of the string is replaced*; further occurrences will be left alone, which I assume is not the intended behavior. (If it is, you should close this issue)

The fix is pretty simple—change the string parameters to RegExes with the `g` (Global match) flag.

**Comment by bsoelch** [comment]
I did not know that JavaScript handles string.replace differently than Java
